<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsEventbus\Config\Env' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Config\\Env'] = new \PrestaShop\Module\PsEventbus\Config\Env();
