<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Handler\\ErrorHandler\\ErrorHandler'] = new \PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler(${($_ = isset($this->services['ps_eventbus']) ? $this->services['ps_eventbus'] : $this->load('getPsEventbusService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Config\\Env']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Config\\Env'] : ($this->services['PrestaShop\\Module\\PsEventbus\\Config\\Env'] = new \PrestaShop\Module\PsEventbus\Config\Env())) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\PsAccountsInstaller\\Installer\\Facade\\PsAccounts']) ? $this->services['PrestaShop\\PsAccountsInstaller\\Installer\\Facade\\PsAccounts'] : $this->load('getPsAccountsService.php')) && false ?: '_'});
