<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ezcacw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ezcacw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0ezcacw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0ezcacw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0ezcacw\appDevDebugProjectContainer([
    'container.build_hash' => '0ezcacw',
    'container.build_id' => '3ab70d17',
    'container.build_time' => 1663128410,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ezcacw');
